alpha = 0.01 # ps^{-1} µm^2
gammalp = 0.001 # ps^{-1}
Gamma = 0.363636363636363636
G = 0.000008 # ps^{-1} µm^2
R = 0.0005 # ps^{-1} µm^2
eta = 0.001 # ???
scale = 6
pumpStrength = 40 # µm^{-2}
sigma = 1.2 # µm
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -60 # µm
endX = 60
startY = -60
endY = 60
m = 0.32 # meV ps^2 µm^{-1}
log = true
copyright = 'Public Domain'
