alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.015
eta = 1
radius = 100
divisions = 4
pumpStrength = 24
sigma = 1.2
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -140
endX = 140
startY = -140
endY = 140
m = 0.32
copyright = 'Public Domain'
wneg = false
