alpha = 0.01
gammalp = 2
Gamma = 1
G = 0.1
R = 2
eta = 1
radius = 120
divisions = 4
pumpStrength = 20
sigma = 1.2
dt = 0.07
samplesX = 1024
samplesY = 1024
startX = -200
endX = 200
startY = -200
endY = 200 
m = 0.5
copyright = 'Public Domain'
