alpha = 0.01
gammalp = 2
Gamma = 1
G = 0.1
R = 2
eta = 1
scale = 12
pumpStrength = 40
sigma = 14
dt = 0.05
samplesX = 1024
samplesY = 1024
startX = -220
endX = 220
startY = -220
endY = 220
m = 0.5
copyright = 'Public Domain'
