alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
pumpStrength = 24
sigma = 2
dt = 0.05
samplesX = 1024
samplesY = 1024
startX = -180
endX = 180
startY = -180
endY = 180
m = 0.32
nframes = 1024
prerun = 12000
intermediaterun = 2000
ndistances = 37
rhomblength0 = 24
rhomblength1 = 12
kind = 'penrose'
copyright = 'Public Domain'
wneg = false
