alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
pumpStrength = 16
sigma = 2.5
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -100
endX = 100
startY = -100
endY = 100
m = 0.32
nframes = 512
prerun = 8000
#intermediaterun = 1000
copyright = 'Public Domain'
