alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
pumpStrength = 16
sigma = 2
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -200
endX = 200
startY = -200
endY = 200
m = 0.32
nframes = 512
prerun = 8000
#intermediaterun = 1000
copyright = 'Public Domain'
