alpha = 0.01
gammalp = 2
Gamma = 1
G = 0.1
R = 2
eta = 1
radius = 200
divisions = 5
pumpStrength = 20
sigma = 0.9
dt = 0.01
samplesX = 1024
samplesY = 1024
startX = -220
endX = 220
startY = -220
endY = 220
m = 0.5
log = true
copyright = 'Public Domain'
