alpha = 0.0004 # µm^{2} ps^{-1}
gammalp = 0.2 # ps^{-1}
Gamma = 0.1 # ps^{-1}
G = 0.002 # µm^2 ps^{-1}
R = 0.016 # µm^2 ps^{-1}
eta = 2 # dimensionless
offset1 = -5 # µm
offset2 = 5 # µm
pumpStrength = 34 # µm^{-2} ps^{-1}
sigma = 1.6 # µm
dt = 0.05 # ps
samplesX = 512
samplesY = 512
startX = -60
endX = 60
startY = -60
endY = 60
m = 0.32 # meV ps^2 µm^{-2} 
prerun = 6000 # steps to run without recording data for dispersion plot, this can help get less artifacts in the dispersion
nframes = 1024 # number of steps to record for dispersion plot
