alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
radius = 90.4665
cutoff = 76.8965
divisions = 4
pumpStrength = 24
sigma = 1.27
dt = 0.05
samplesX = 1024
samplesY = 1024
startX = -120
endX = 120
startY = -120
endY = 120
m = 0.32
copyright = 'Public Domain'
wneg = false
nframes = 8000
