alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.015
eta = 1
radius = 136
divisions = 4
pumpStrength = 23
sigma = 1.2
dt = 0.2
samplesX = 512
samplesY = 512
startX = -170
endX = 170
startY = -170
endY = 170
m = 0.32
nframes = 512
prerun = 6000
intermediaterun = 1000
copyright = 'Public Domain'
wneg = false
