alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.015
eta = 1
radius = 160
divisions = 5
pumpStrength = 26
sigma = 1.2
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -180
endX = 180
startY = -180
endY = 180
m = 0.32
copyright = 'Public Domain'
wneg = false
