alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.03
eta = 1
pumpStrength = 38
sigma = 1.2
dt = 0.3
samplesX = 512
samplesY = 512
startX = -160
endX = 160
startY = -160
endY = 160
m = 0.32
nframes = 512
prerun = 8000
intermediaterun = 1000
copyright = 'Public Domain'
wneg = false
