alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
radius = 136
divisions = 4
pumpStrength = 23
sigma = 2
dt = 0.05
samplesX = 512
samplesY = 512
startX = -50
endX = 50
startY = -50
endY = 50
m = 0.32
nframes = 1024
prerun = 12000
intermediaterun = 2000
ndistances = 21
rhomblength0 = 15.941
rhomblength1 = 15.9406
copyright = 'Public Domain'
wneg = false
