alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
radius = 136
divisions = 4
pumpStrength = 24
sigma = 2
dt = 0.05
samplesX = 512
samplesY = 512
startX = -40
endX = 40
startY = -40
endY = 40
m = 0.32
nframes = 1024
prerun = 12000
intermediaterun = 2000
ndistances = 37
rhomblength0 = 24
rhomblength1 = 12
type = 'thick'
copyright = 'Public Domain'
wneg = false
