alpha = 0
gammalp = 0
Gamma = 0
G = 0
R = 0
eta = 0
radius = 200
divisions = 1
pumpStrength = 0
sigma = 0.9
dt = 0.05
samplesX = 256
samplesY = 256
startX = -20
endX = 20
startY = -20
endY = 20
m = 0.5
copyright = 'Public Domain'
