alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.001
R = 0.015
eta = 1
radius = 220
divisions = 5
pumpStrength = 22
sigma = 1.1
dt = 0.1
samplesX = 1024
samplesY = 1024
startX = -140
endX = 140
startY = -140
endY = 140
m = 0.32
copyright = 'Public Domain'
wneg = false
