alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.015
eta = 1
pumpStrength = 16
sigma = 1.2
dt = 0.2
samplesX = 512
samplesY = 512
startX = -120
endX = 120
startY = -120
endY = 120
m = 0.32
nframes = 512
prerun = 4000
intermediaterun = 1000
copyright = 'Public Domain'
wneg = false
