alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.015
eta = 2
pumpStrength = 24
sigma = 1.2
dt = 0.2
samplesX = 512
samplesY = 512
startX = -140
endX = 140
startY = -140
endY = 140
m = 0.32
nframes = 512
prerun = 4000
intermediaterun = 1000
copyright = 'Public Domain'
wneg = false
