alpha = 0.0004
gammalp = 0.2
Gamma = 0.1
G = 0.002
R = 0.016
eta = 2
pumpStrength = 24
sigma = 2
dt = 0.05
samplesX = 1024
samplesY = 1024
startX = -60
endX = 60
startY = -60
endY = 60
m = 0.32
nframes = 1024
prerun = 3072
intermediaterun = 2000
ndistances = 3
rhomblength0 = 24
rhomblength1 = 12
kind = 'thin'
copyright = 'Public Domain'
wneg = false
